name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.FASTHOST_KEY }}

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Install Node.js Dependencies
        run: npm install

      - name: Deploy to server
        run: scp -r ./* root@77.68.55.121:/var/www/test-kontrack

      - name: Restart Nginx
        run: ssh user@your-server-ip "sudo systemctl reload nginx"
