name: Run Kontrack Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: dev
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Copy .env file
        run: cp .env.example .env

      - name: Configure .env with secrets
        run: |
          sed -i "s/DB_HOST=.*/DB_HOST=127.0.0.1/" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=root/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=pass/" .env
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=dev/" .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test
